export class Location{
    // properties list :
    //id_                   id generated by the coordinates
    private _id : string = ''
    // horizontal_          horizontal line
    protected _horizontal : number ;
    // vertical_            vertical line
    protected _vertical : number ;

    constructor (horizontal_ : number,vertical_ : number){

        this._horizontal = horizontal_;
        this._vertical = vertical_;

        if(horizontal_>=10) this._id = ''+horizontal_;
        else this._id = '0'+horizontal_;
        if(vertical_>=10) this._id += vertical_;
        else this._id += '0'+vertical_;

    }

    //getters & setters
    get horizontal() : number {
        return this._horizontal;
    }
    set horizontal(value : number){
        this._horizontal = value;
    }
    get vertical() : number {
        return this._vertical;
    }
    set vertical(value : number ){
        this._vertical = value;
    }
    get id(){
      return this._id;
    }


    idToNums( id : string ){
        var nums : number[] = [Number.parseInt(id.slice(0,2)),Number.parseInt(id.slice(2,4))]
        return nums;
    }
    numsToId( nums : number[] ){
        var id : string = '';
        if(nums[0]>=10) id = ''+nums[0];
        else id = '0'+nums[0];
        if(nums[1]>=10) id += nums[1];
        else id += '0'+nums[1];
        return id
    }

    equal(loc):boolean{
        return (this._horizontal==loc.horizontal && this.vertical==loc.vertical);
    }
}
